"""Initial migration

Revision ID: 3bc46f673a4a
Revises: 
Create Date: 2021-05-31 13:39:57.549060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc46f673a4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist',
                    sa.Column('artistid', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('city', sa.String(length=120), nullable=True),
                    sa.Column('state', sa.String(length=120), nullable=True),
                    sa.Column('phone', sa.String(length=120), nullable=True),
                    sa.Column('genres', sa.String(length=120), nullable=True),
                    sa.Column('image_link', sa.String(
                        length=500), nullable=True),
                    sa.Column('facebook_link', sa.String(
                        length=120), nullable=True),
                    sa.PrimaryKeyConstraint('artistid')
                    )
    op.create_table('Venue',
                    sa.Column('venueid', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('city', sa.String(length=120), nullable=True),
                    sa.Column('state', sa.String(length=120), nullable=True),
                    sa.Column('address', sa.String(length=120), nullable=True),
                    sa.Column('phone', sa.String(length=120), nullable=True),
                    sa.Column('image_link', sa.String(
                        length=500), nullable=True),
                    sa.Column('facebook_link', sa.String(
                        length=120), nullable=True),
                    sa.PrimaryKeyConstraint('venueid')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Venue')
    op.drop_table('Artist')
    # ### end Alembic commands ###
