"""empty message

Revision ID: 46fd015cc9d5
Revises: d6cfdcefb16c
Create Date: 2021-06-01 12:25:23.957232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fd015cc9d5'
down_revision = 'd6cfdcefb16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shows', 'venueid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Shows', 'artistid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'Shows', 'Venue', ['venueid'], ['venueid'])
    op.create_foreign_key(None, 'Shows', 'Artist', ['artistid'], ['artistid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.alter_column('Shows', 'artistid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Shows', 'venueid',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
