"""empty message

Revision ID: 5c73f7f53d60
Revises: 46fd015cc9d5
Create Date: 2021-06-02 10:48:42.606233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c73f7f53d60'
down_revision = '46fd015cc9d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genres',
    sa.Column('genreid', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('genreid')
    )
    op.create_table('GenreAssoc',
    sa.Column('genreassocid', sa.Integer(), nullable=False),
    sa.Column('genreid', sa.Integer(), nullable=False),
    sa.Column('venueid', sa.Integer(), nullable=True),
    sa.Column('artistid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artistid'], ['Artist.artistid'], ),
    sa.ForeignKeyConstraint(['genreid'], ['Genres.genreid'], ),
    sa.ForeignKeyConstraint(['venueid'], ['Venue.venueid'], ),
    sa.PrimaryKeyConstraint('genreassocid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GenreAssoc')
    op.drop_table('Genres')
    # ### end Alembic commands ###
