"""empty message

Revision ID: 76e25262ef7a
Revises: a5f1e9aa9a75
Create Date: 2021-06-09 07:45:28.615801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e25262ef7a'
down_revision = 'a5f1e9aa9a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('States',
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('States')
    # ### end Alembic commands ###
