"""empty message

Revision ID: c099be4b3e67
Revises: 76e25262ef7a
Create Date: 2021-06-09 07:54:19.570901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c099be4b3e67'
down_revision = '76e25262ef7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Artist', 'States', ['state'], ['state'])
    op.create_foreign_key(None, 'Venue', 'States', ['state'], ['state'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    # ### end Alembic commands ###
